
# If not running interactively, don't do anything - this has burnt me in the past
case $- in
    *i*) ;;
      *) return;;
esac

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize


# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"



# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'


# My Stuff

alias python='python3'

source ~/.git-prompt.sh

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export GIT_PS1_SHOWCOLORHINTS=1
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1

# Eric's Bullshit
export PROMPT_COMMAND='__git_ps1 "\[\e[0;32m\]\u\[\e[0;31m\]@\[\e[1;36m\]\h:\[\e[1;33m\]\w\[\e[0;37m\]" "\\\$ "'
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

gcd() { cd "$(git rev-parse --show-toplevel)"/"$@"; }
